-- MySQL Script generated by MySQL Workbench
-- 10/18/17 19:36:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usu_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usu_usuario` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `usu_nome_completo` VARCHAR(100) NOT NULL,
  `usu_email` VARCHAR(100) NOT NULL,
  `usu_senha` VARCHAR(45) NOT NULL,
  `usu_admin` INT NOT NULL,
  `usu_telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`usu_id`),
  UNIQUE INDEX `email_UNIQUE` (`usu_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipamento_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipamento_tipo` (
  `tpe_id` INT NOT NULL AUTO_INCREMENT,
  `tpe_descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`tpe_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equ_equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equ_equipamento` (
  `equ_id` INT NOT NULL AUTO_INCREMENT,
  `equ_descricao` VARCHAR(45) NULL,
  `equ_ativo` INT NULL,
  `equipamento_tipo_tpe_id` INT NOT NULL,
  `equ_observacoes` VARCHAR(45) NULL,
  PRIMARY KEY (`equ_id`),
  INDEX `fk_equ_equipamento_equipamento_tipo1_idx` (`equipamento_tipo_tpe_id` ASC),
  CONSTRAINT `fk_equ_equipamento_equipamento_tipo1`
    FOREIGN KEY (`equipamento_tipo_tpe_id`)
    REFERENCES `mydb`.`equipamento_tipo` (`tpe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lab_laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lab_laboratorio` (
  `lab_id` INT NOT NULL AUTO_INCREMENT,
  `lab_descricao` VARCHAR(45) NOT NULL,
  `lab_observacao` TEXT NULL,
  PRIMARY KEY (`lab_id`),
  UNIQUE INDEX `lab_descricao_UNIQUE` (`lab_descricao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`res_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`res_reserva` (
  `res_id` INT NOT NULL AUTO_INCREMENT,
  `res_data_hora` TIMESTAMP NOT NULL,
  `res_data_reserva_inicial` DATETIME NOT NULL,
  `res_data_reserva_final` DATETIME NOT NULL,
  `usu_usuario_id_usuario` INT NOT NULL,
  `res_observacao` TEXT NULL,
  `equ_id` INT NULL,
  `llab_id` INT NULL,
  PRIMARY KEY (`res_id`),
  INDEX `fk_res_reserva_usu_usuario_idx` (`usu_usuario_id_usuario` ASC),
  INDEX `fk_res_reserva_equ_equipamento1_idx` (`equ_id` ASC),
  INDEX `fk_res_reserva_lab_laboratorio1_idx` (`llab_id` ASC),
  CONSTRAINT `fk_res_reserva_usu_usuario`
    FOREIGN KEY (`usu_usuario_id_usuario`)
    REFERENCES `mydb`.`usu_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_res_reserva_equ_equipamento1`
    FOREIGN KEY (`equ_id`)
    REFERENCES `mydb`.`equ_equipamento` (`equ_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_res_reserva_lab_laboratorio1`
    FOREIGN KEY (`llab_id`)
    REFERENCES `mydb`.`lab_laboratorio` (`lab_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`par_paramentros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`par_paramentros` (
  `par_id` INT NOT NULL AUTO_INCREMENT,
  `par_descricao` VARCHAR(100) NOT NULL,
  `par_valor` INT NOT NULL,
  `par_observacao` TEXT NULL,
  PRIMARY KEY (`par_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mel_melhoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mel_melhoria` (
  `mel_id` INT NOT NULL AUTO_INCREMENT,
  `mel_observacao` TEXT NULL,
  `mel_data_hora` TIMESTAMP NOT NULL,
  `usu_id` INT NOT NULL,
  `equ_id` INT NOT NULL,
  `lab_id` INT NOT NULL,
  `mel_resposta` TEXT NULL,
  `mel_resolvido` INT NULL,
  PRIMARY KEY (`mel_id`, `equ_id`),
  INDEX `fk_mel_melhoria_usu_usuario1_idx` (`usu_id` ASC),
  INDEX `fk_mel_melhoria_equ_equipamento1_idx` (`equ_id` ASC),
  INDEX `fk_mel_melhoria_lab_laboratorio1_idx` (`lab_id` ASC),
  CONSTRAINT `fk_mel_melhoria_usu_usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `mydb`.`usu_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mel_melhoria_equ_equipamento1`
    FOREIGN KEY (`equ_id`)
    REFERENCES `mydb`.`equ_equipamento` (`equ_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mel_melhoria_lab_laboratorio1`
    FOREIGN KEY (`lab_id`)
    REFERENCES `mydb`.`lab_laboratorio` (`lab_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
